// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/amd-radeon.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const AMD_RADEON_MODELS: ModelCatalog<typeof values, "amd-radeon"> =
	flattenModelCatalog("amd-radeon", values);
